var app = angular.module("myApp", ['ui.bootstrap', 'ngAnimate', 'ngRoute', 'ui.uploader', 'djCards']);

app.config(function ($routeProvider) {
    // Routes wait for the card data so templates never render half-loaded.
    var loadCards = ['cardService', function (cardService) { return cardService.ready(); }];

    $routeProvider
        .when('/', {
            templateUrl: 'main.html',
            controller: 'MainCtrl',
            resolve: { cards: loadCards }
        })
        .when('/char/:id', {
            templateUrl: 'character.html',
            controller: 'CharCtrl',
            resolve: { cards: loadCards }
        });
});


app.factory("appData", function () {
    var appData = {
        partyGold: 0,
        partyConquest: 0,
        handSwitch: [true, false, false, false, false],
        currentDeck: 'Store',
        currentSkillDeck: 'Fighter',
        currentFeatDeck: 'Fighter',
        characters: [],
        upgradeItems: [
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Wounds Copper" },
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Wounds Silver" },
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Wounds Gold" },
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Fatigue Copper" },
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Fatigue Silver" },
            { type: 'upgrade', qty: 4, src: 'Images/Upgrades/', name: "Maximum Fatigue Gold" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Melee Power" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Melee Power Silver" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Melee Power Gold" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Ranged Power" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Ranged Power Silver" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Ranged Power Gold" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Magic Power" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Magic Power Silver" },
            { type: 'upgrade', qty: 99, src: 'Images/Upgrades/', name: "Magic Power Gold" }
        ],
        storeItems: [
            { type: 'store', qty: 12, src: 'Images/Items/Store/', isItemTapped: false, name: "Potion of Health" },
            { type: 'store', qty: 12, src: 'Images/Items/Store/', isItemTapped: false, name: "Potion of Vitality" },
            { type: 'store', qty: 12, src: 'Images/Items/Store/', isItemTapped: false, name: "Potion of Power" },
            { type: 'store', qty: 12, src: 'Images/Items/Store/', isItemTapped: false, name: "Potion of Invisibility" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Axe" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Blinding Light" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Bow" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Chain Mail" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Crossbow" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Curse Doll" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Dagger" },
            { type: 'store', qty: 1, src: 'Images/Items/Store/', isItemTapped: false, name: "Ghost Armor" },
            { type: 'store', qty: 1, src: 'Images/Items/Store/', isItemTapped: false, name: "Hammer" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Immolation" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Iron Shield" },
            { type: 'store', qty: 3, src: 'Images/Items/Store/', isItemTapped: false, name: "Leather Armor" },
            { type: 'store', qty: 3, src: 'Images/Items/Store/', isItemTapped: false, name: "Mage Staff" },
            { type: 'store', qty: 1, src: 'Images/Items/Store/', isItemTapped: false, name: "Morning Star" },
            { type: 'store', qty: 1, src: 'Images/Items/Store/', isItemTapped: false, name: "Remove Curse" },
            { type: 'store', qty: 1, src: 'Images/Items/Store/', isItemTapped: false, name: "Ring of Protection" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Sling" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Sunburst" },
            { type: 'store', qty: 3, src: 'Images/Items/Store/', isItemTapped: false, name: "Sword" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Throwing Knife" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Tunic" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Walking Stick" },
            { type: 'store', qty: 2, src: 'Images/Items/Store/', isItemTapped: false, name: "Wizards Robe" }],
        copperItems: [
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Archers Charm" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Axe of Returning" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Backbiter" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Bane" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Belt of Strength" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Bone Blade" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Cloak of Deception" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Cone of Fire" },
            { type: 'Copper', qty: 2, src: 'Images/Items/Copper/', isItemTapped: false, name: "Crystal of Tival" },
            { type: 'Copper', qty: 2, src: 'Images/Items/Copper/', isItemTapped: false, name: "Crystal Shield" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Crystalize" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Dragontooth Hammer" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Dwarven Fire Bombs" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Elven Robe" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Falcons Claw" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Gauntlets of Power" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Great Bow" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Heavy Leather Armor" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Knuckle Dagger" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Leviathan" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Mace of Aver" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Magic Bow" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Mana Weave" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Minor Healing" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Pacify" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Pack of Holding" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Plate Mail" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Ring of Quickness" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Ripper" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Screaming Eagle Staff" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Shadow Blade" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Shillelagh" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Skull Shield" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Staff of Punishment" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Staff of the Grave" },
            { type: 'Copper', qty: 2, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 1" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 2" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 3" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 4" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 5" },
            { type: 'Copper', qty: 1, src: 'Images/Items/Copper/', isItemTapped: false, name: "Treasure Cache 6" }],
        silverItems: [
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Aldars Mirror" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Amulet of Healing" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Barbed Dagger" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Beastman Fetish" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Black Widows Web" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Bo Stick" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Bottle Imp" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Bow of Bones" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Bow of the Hawk" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Bracers of Might" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Cloak of Mists" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Dragons Breath" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Drain Life" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Elven Boots" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Enchanted Breastplate" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Eyes of Thara" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Flute of Repose" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Flying Death" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Golden Armor" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Greater Healing" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Grinding Axe" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Ice Storm" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Lifedrinker" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Mace of Kellos" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Mirror Shield" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Petrify" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Ring of Freedom" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Robe of Kellos" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Scorpion Helmet" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Scythe of Reaping" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Serpent Blade" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Shield of Light" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Skullcracker" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Staff of Fire" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 1" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 2" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 3" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 4" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 5" },
            { type: 'Silver', qty: 1, src: 'Images/Items/Silver/', isItemTapped: false, name: "Treasure Cache 6" }],
        goldItems: [
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Bloody Dagger" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Bracers of Accuracy" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Curse of Rot" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Deflect" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Dragon Scale Mail" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Elven Bow" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Elven Cloak" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Flame Strike" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Frost Axe" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Hammer of Doom" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Jinns Lamp" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Longspear" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Mithril Breastplate" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Rage Blade" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Ring of the Arcane" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Robe of Shadows" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Scarab of Death" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Sheath of Might" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Shield of the Warrior" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Sorcerous Orb" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Spirit Spear" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Staff of Knowledge" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Star of Kellos" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Stone Cutter" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Superior Healing" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "The Knights Ring" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Wings of Regiroth" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Wishing Ring" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Word of Vaal" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Treasure Cache 1" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Treasure Cache 2" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Treasure Cache 3" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Treasure Cache 4" },
            { type: 'Gold', qty: 1, src: 'Images/Items/Gold/', isItemTapped: false, name: "Treasure Cache 5" }],
        heroes: [{
            name: "Andira Runehand",
            trait: "When Andira Runehand makes a Magic attack on an adjacent enemy, she gains Pierce 2.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Arvel Worldwalker",
            trait: "When a glyph has been activated, Arvel may draw 2 feat cards instead of just 1. Arvel's maximum feat hand size is increased to 6.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [],
            upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Aurim",
            trait: "During his turn, Aurim may discard one of his equipped potions and exchange it for another potion of any type from the bank. He may use this ability as often as he likes.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 0,
            wizardryTraits: 2,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Battlemage Jaes",
            trait: "Battlemage Jaes may equip Runes even while wearing Armor that would ordinarily prevent it.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 2,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 2, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 0,
            wizardryTraits: 2,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Bogran the Shadow",
            trait: "When Bogran the Shadow attacks an enemy that did not have line of sight to him at the start of the current turn, he gains +2 damage.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        }, {
            name: "Brother Gherinn",
            trait: "Before rolling for any attack, Brother Gherinn may sacrifice 1 wound to make it an aimed attack.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 0,
            wizardryTraits: 2,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Brother Glyr",
            trait: "Brother Glyr always receives an extra 2 movement points each turn, regardless of which action he declares.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 5,
            fatigueCap: 5,
            speed: 2,
            armor: 3,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 1,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Challara",
            trait: "Brightblaze is your familiar. Take the Brightblaze token at the start of the game. Brightblaze's speed is 4. Once per area, Brightblaze may make a magic Breath attack, rolling one white die and one green die, ignoring armor.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 4,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Corbin",
            trait: "Corbin takes 1 fewer wound than usual each time he is wounded.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 5,
            fatigueCap: 5,
            speed: 3,
            armor: 2,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Eliam",
            trait: "Once per turn, Eliam may spend 3 fatigue before making a Melee attack to give that attack the Sweep ability.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 3,
            fatigueCap: 3,
            speed: 5,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 2, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 0,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Grey Ker",
            trait: "Grey Ker can change his declared action during his turn as long as his total movement and attacks during the turn do not exceed those allowed by his new action.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 3, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 2,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Hugo the Glorious",
            trait: "	Hugo the Glorious cannot make Magic attacks or spend fatigue for extra movement.",
            isTapped: false,
            wounds: 20,
            woundsCap: 20,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Ispher",
            trait: "	At the start of his turn, Ispher recovers 1 wound. Ispher is immune to Poison.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 0,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Jonas the Kind",
            trait: "Once per turn, Eliam may spend 3 fatigue before making a Melee attack to give that attack the Sweep ability.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 0,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 0,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Karnon",
            trait: "Karnon has the Tread Ice ability and is immune to Frost and Fear.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 5, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Kirga",
            trait: "The Overlord cannot spawn monsters within 5 spaces of Kirga, regardless of line of sight or other effects.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 3, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 3,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Krutzbeck",
            trait: "While Krutzbeck has 4 or fewer wounds remaining, he gains +2 armor and +2 damage.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Landrec the Wise",
            trait: "Landrec the Wise receives 2 free surges on every attack roll.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 3,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 1,
            wizardryTraits: 2,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Laughin Buldar",
            trait: "Laughin Buldar may use a single two-handed melee weapon as if it were a one-handed weapon.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 1,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Laurel of Bloodwood",
            trait: "After rolling a Ranged attack, Laurel may spend 1 fatigue to convert any extra range she rolled into damage on one-for-one basis.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Lindel",
            trait: "Once per area, Lindel may discard one of his skill cards, drawing a new skill card of the same type to replace it.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 1,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 2, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 1,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Lord Hawthorne",
            trait: "Lord Hawthorne has the Reach ability.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Lyssa",
            trait: "When Lyssa is attacked, she may force attacker to re-roll 1 Green, 1 Yellow or 1 Black die of her choice. Lyssa cannot use this ability when she is dodging, and she cannot use it when the attack is an aimed attack.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 1,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Mad Carthos",
            trait: "When making Magic attacks, Mad Carthos gains +2 damage.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Mordrog",
            trait: "Mordrog recovers 1 fatigue each time he is wounded.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Nanok of the Blade",
            trait: "	Nanok of the Blade cannot wear Armor. * is equal to 2 + Nanok of the Blade's melee trait (the number of power dice he rolls when making a Melee attack).",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: '*',
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 1,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Nara the Fang",
            trait: "Enemy figures damaged by one of Nara's attacks suffer 1 extra damage for each space they occupy beyond the first.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 1,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Okaluk and Rakash",
            trait: "Okaluk and Rakash have the Stealth ability.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 2,
            fatigueCap: 2,
            speed: 6,
            armor: 0,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 1,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "One Fist",
            trait: "One Fist only has one hand for the purposes of equipping items. He may always make one Melee attack, rolling 1 Red and 1 Green die, in addition to his normal action.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 2,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Red Scorpion",
            trait: "At the start of her turn, Red Scorpion may spend 1 fatigue to recover 1 wound or suffer 1 wound to recover 1 fatigue.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 1,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Ronan of the Wild",
            trait: "Pico is your companion. Take the Pico token at the start of the game.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 1,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Runemaster Thorn",
            trait: "Once per turn, Runemaster Thorn may spend 5 movement points to move to any empty space in his line of sight.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Runewitch Astarra",
            trait: "Glyphs activate when Runewitch Astarra moves within 6 spaces of them.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Sahla",
            trait: "At the start of his turn, Sahla may spend 2 fatigue to discard one effect token that is placed on him. The discarded token does not take effect.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 2, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Shiver",
            trait: "During the Overlord's turn, Shiver has the Aura 4 ability.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 0,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Silhouette",
            trait: "While Silhouette has a readied order, she may spend 2 fatigue to exchange it for a different order at any time.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 5,
            fatigueCap: 5,
            speed: 5,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 3, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 3,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Sir Valadir",
            trait: "When Sir Valadir spends fatigue to add dice to an attack roll, he adds 2 power dice instead of 1 (up to the normal limit of 5 power dice).",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 1,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Spiritspeaker Mok",
            trait: "Mordrog recovers 1 fatigue each time he is wounded	The overlord's cost to play cards is increased by 1 threat token per card.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 0,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 2, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 0,
            wizardryTraits: 2,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Steelhorns",
            trait: "Steelhorns can make one Melee attack when he declares a Run action. He must move in a straight line and end his movement after making the attack.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 4,
            armor: 1,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [], feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Tahlia",
            trait: "When Tahlia discards a Guard order to make an interrupt attack, she may move a number of spaces equal to her speed before or after attacking.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Tatianna",
            trait: "Once per area, Tatianna may return to town at the start of the Overlord's turn without using a glyph.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 5,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 3, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 3,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Tetherys",
            trait: "Tetherys may change her target after rolling for an attack.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 3,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Tobin Farslayer",
            trait: "When Tobin makes a successful attack, add the distance to his target to his damage. Tobin cannot make ranged attacks against adjacent figures.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 3, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 3,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Trenloe the Strong",
            trait: "When Trenloe the Strong attacks, you may re-roll 1 Green, 1 Yellow or 1 Black die of your choice. Trenloe cannot use this ability if he is aiming or if his target is dodging.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 3,
            fatigueCap: 3,
            speed: 3,
            armor: 2,
            meleePower: 3, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 0, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 3,
            subterfugeTraits: 0,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Truthseer Kel",
            trait: "Obstacles and other figures do not block Truthseer Kel's line of sight. Kel ignores the Shadowcloak ability.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 3, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 0,
            subterfugeTraits: 0,
            wizardryTraits: 3,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Varikas the Dead",
            trait: "At the start of his turn, Varikas the Dead recovers 1 fatigue.",
            isTapped: false,
            wounds: 16,
            woundsCap: 16,
            fatigue: 4,
            fatigueCap: 4,
            speed: 3,
            armor: 2,
            meleePower: 2, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 0, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 2,
            subterfugeTraits: 0,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Vyrah the Falconer",
            trait: "Skye is your familiar. Take the Skye marker at the start of the game.",
            isTapped: false,
            wounds: 12,
            woundsCap: 12,
            fatigue: 4,
            fatigueCap: 4,
            speed: 4,
            armor: 1,
            meleePower: 0, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 2, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 2,
            wizardryTraits: 0,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        },
        {
            name: "Zyla",
            trait: "At the start of his turn, Varikas the Dead recovers 1 fatigue.",
            isTapped: false,
            wounds: 8,
            woundsCap: 8,
            fatigue: 5,
            fatigueCap: 5,
            speed: 4,
            armor: 0,
            meleePower: 1, meleeSilverPower: 0, meleeGoldPower: 0,
            rangedPower: 1, rangedSilverPower: 0, rangedGoldPower: 0,
            magicPower: 1, magicSilverPower: 0, magicGoldPower: 0,
            fighterTraits: 1,
            subterfugeTraits: 1,
            wizardryTraits: 1,
            skills: [],
            equipped: [],
            bag: [],
            feats: [], upgrades: [],
            bleedStatus: 0,
            dazeStatus: 0,
            poisonStatus: 0,
            curseStatus: 0,
            stunStatus: 0,
            burnStatus: 0,
            webStatus: 0,
            freezeStatus: 0
        }],

    };
    return appData;

});